# Generated by Django 3.1.5 on 2021-01-20 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gotapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('wysokosc', models.FloatField()),
                ('szerokoscGeo', models.FloatField()),
                ('dlugoscGeo', models.FloatField()),
                ('grupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotapp.grupagorska')),
            ],
            options={
                'ordering': ['nazwa', 'grupa'],
            },
        ),
    ]
