# Generated by Django 3.1.5 on 2021-01-20 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gotapp', '0002_punkt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='punkt',
            options={'ordering': ['nazwa']},
        ),
    ]
