# Generated by Django 3.1.5 on 2021-01-20 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gotapp', '0003_auto_20210121_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odcinek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('przewyzszenie', models.FloatField()),
                ('dlugosc', models.FloatField()),
                ('czyAktywny', models.BooleanField()),
                ('dataPonOtw', models.DateField(blank=True)),
                ('punktacja', models.IntegerField(blank=True)),
                ('rokAkt', models.DateField(blank=True)),
                ('discriminator', models.CharField(max_length=10)),
                ('koniec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konczone', to='gotapp.punkt')),
                ('poczatek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zaczynane', to='gotapp.punkt')),
            ],
            options={
                'ordering': ['nazwa', 'dlugosc', 'czyAktywny'],
            },
        ),
    ]
