# Generated by Django 3.1.5 on 2021-01-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotapp', '0004_odcinek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odcinek',
            name='dataPonOtw',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odcinek',
            name='punktacja',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odcinek',
            name='rokAkt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
