# Generated by Django 3.1.5 on 2021-01-21 12:27

from django.db import migrations, models
import django.db.models.deletion
import gotapp.models.osoba


class Migration(migrations.Migration):

    dependencies = [
        ('gotapp', '0005_auto_20210121_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=40)),
                ('nazwisko', models.CharField(max_length=40)),
                ('plec', models.CharField(blank=True, max_length=1, null=True, validators=[gotapp.models.osoba.plecValidator])),
                ('dataUr', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('haslo', models.CharField(max_length=64)),
                ('czyAkt', models.BooleanField()),
                ('czyNiepeln', models.BooleanField()),
                ('miasto', models.CharField(blank=True, max_length=100, null=True)),
                ('ulica', models.CharField(blank=True, max_length=100, null=True)),
                ('nrDomu', models.IntegerField(blank=True, null=True)),
                ('nrMieszk', models.IntegerField(blank=True, null=True)),
                ('kodPoczt', models.CharField(blank=True, max_length=64, null=True)),
                ('nrTel', models.CharField(max_length=12)),
                ('discriminator', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['discriminator', 'nazwisko', 'imie'],
            },
        ),
        migrations.CreateModel(
            name='OdcinekWeryfikowany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataWer', models.DateField(blank=True, null=True)),
                ('czyZwer', models.BooleanField(blank=True, null=True)),
                ('nrPorz', models.IntegerField()),
                ('odcinek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotapp.odcinek')),
                ('przod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotapp.osoba')),
            ],
            options={
                'ordering': ['nrPorz'],
            },
        ),
    ]
