# Generated by Django 3.1.5 on 2021-01-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotapp', '0007_auto_20210121_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='nrTel',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
