# Generated by Django 3.1.5 on 2021-01-21 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gotapp', '0008_auto_20210121_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legitymacja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminWaz', models.DateField()),
                ('dataPrzyznania', models.DateField()),
                ('przod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legitymacja', to='gotapp.osoba')),
            ],
        ),
    ]
