# Generated by Django 3.1.5 on 2021-01-21 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gotapp', '0009_legitymacja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legitymacja',
            name='przod',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legitymacja', to='gotapp.osoba'),
        ),
    ]
