# Generated by Django 3.1.5 on 2021-01-21 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gotapp', '0011_auto_20210121_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ksiazeczka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punktacja', models.IntegerField()),
                ('turysta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ksiazeczka', to='gotapp.osoba')),
            ],
        ),
        migrations.CreateModel(
            name='RodzajOdznaki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['rodzaj'],
            },
        ),
        migrations.CreateModel(
            name='StopienOdznaki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopien', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['stopien'],
            },
        ),
        migrations.AlterField(
            model_name='uprawnienie',
            name='legitymacja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uprawnienie', to='gotapp.legitymacja'),
        ),
        migrations.CreateModel(
            name='Odznaka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPrzyznania', models.DateField(blank=True, null=True)),
                ('wyPkt', models.IntegerField()),
                ('czyRozp', models.BooleanField(blank=True, null=True)),
                ('ksiazeczka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odznaki', to='gotapp.ksiazeczka')),
                ('rodzaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotapp.rodzajodznaki')),
                ('stopien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotapp.stopienodznaki')),
            ],
            options={
                'ordering': ['dataPrzyznania'],
            },
        ),
    ]
