# Generated by Django 3.1.5 on 2021-01-21 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gotapp', '0012_auto_20210121_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazeczka',
            name='turysta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ksiazeczka', to='gotapp.osoba'),
        ),
        migrations.AlterField(
            model_name='uprawnienie',
            name='legitymacja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotapp.legitymacja'),
        ),
    ]
