# Generated by Django 3.1.5 on 2021-01-21 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gotapp', '0013_auto_20210121_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprawnienie',
            name='legitymacja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uprawnienia_set', to='gotapp.legitymacja'),
        ),
    ]
