# Generated by Django 3.1.5 on 2021-01-21 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gotapp', '0014_auto_20210121_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uczestnictwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(blank=True, max_length=2000, null=True)),
                ('turysta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotapp.osoba')),
            ],
        ),
        migrations.CreateModel(
            name='Wycieczka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=40)),
                ('dataPocz', models.DateField()),
                ('dataKonc', models.DateField()),
                ('uczestnicy', models.ManyToManyField(through='gotapp.Uczestnictwo', to='gotapp.Osoba')),
            ],
            options={
                'ordering': ['nazwa', 'dataPocz', 'dataKonc'],
            },
        ),
        migrations.AddField(
            model_name='uczestnictwo',
            name='wycieczka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotapp.wycieczka'),
        ),
        migrations.AddField(
            model_name='osoba',
            name='wycieczki',
            field=models.ManyToManyField(through='gotapp.Uczestnictwo', to='gotapp.Wycieczka'),
        ),
    ]
