# Generated by Django 3.1.5 on 2021-01-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotapp', '0019_auto_20210123_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odcinek',
            name='czyAktywny',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='odcinek',
            name='discriminator',
            field=models.CharField(default='NORM', max_length=10),
        ),
    ]
