# Generated by Django 3.1.5 on 2021-01-23 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotapp', '0020_auto_20210123_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odcinek',
            name='rokAkt',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
