# Generated by Django 3.1.5 on 2021-01-23 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotapp', '0022_auto_20210123_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odcinek',
            name='rokAkt',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
